-- ORDERCODE 시퀀스 작성
CREATE SEQUENCE ordercodeseq;

-- ORDERCODE 테이블 작성
CREATE TABLE ORDERCODE(
ORDERNUM NUMBER PRIMARY KEY,
ORDERWHERE VARCHAR2(45) NOT NULL,
ORDERIN VARCHAR2(45),
ORDERDATE DATE,
COUPON VARCHAR2(45)
);
-- FK설정(ORDERNUM -> ORDERCODE)
ALTER TABLE ORDERNUM  
ADD CONSTRAINT ORDERNUM FOREIGN KEY(ORDERNUM) REFERENCES ORDERCODE(ORDERNUM);

-- ORDERCODE 테이블 확인
SELECT * FROM ORDERCODE ;

-- ORDERCODE 테이블 값 넣기
INSERT INTO ORDERCODE VALUES ('1','매장','Y','23.02.14','Y');

-- ORDERNUM 시퀀스 생성
CREATE SEQUENCE ORDERNUMSEQ;

-- ORDERNUM 테이블 생성
CREATE TABLE ORDERNUM(
IDX NUMBER PRIMARY KEY,
FOODSTOCK NUMBER,
ORDERCOUNT NUMBER,
ORDERNUM NUMBER,
FOODNUM VARCHAR2(45)
);

SELECT * FROM ORDERNUM;

DROP TABLE ORDERNUM;

-- ADMIN 시퀀스 생성
CREATE SEQUENCE ADMINPWSEQ;
-- ADMIN 테이블 생성
CREATE TABLE ADMIN(
ADMINPW NUMBER NOT NULL PRIMARY KEY
);

-- MENU 시퀀스 생성
CREATE SEQUENCE MENUSEQ;

-- MENU 테이블 생성
CREATE TABLE MENU(
FOODNUM VARCHAR2(45) PRIMARY KEY,
FOODNAME VARCHAR2(100) NOT NULL,
FOODTYPE VARCHAR2(45) NOT NULL,
FOODPRICE NUMBER NOT NULL,
FOODSOLDOUT VARCHAR(45),
FOODLEV NUMBER NOT NULL
);

SELECT * FROM MENU ;

ALTER TABLE MENU ADD(FOODLEV NUMBER(10));

-- FK설정(ORDERNUM -> MENU)
ALTER TABLE ORDERNUM
ADD CONSTRAINT FOODNUM FOREIGN KEY(FOODNUM) REFERENCES MENU(FOODNUM);

-- MENU 테이블 확인
SELECT * FROM MENU;

DROP TABLE MENU;

DELETE FROM MENU WHERE FOODNUM = 'B02';

-- MENU 테이블 값 넣기
INSERT INTO MENU VALUES('A01', '에스프레소', 'COFFEE', 2500, 'N', 1);
INSERT INTO MENU VALUES('A02', '아메리카노', 'COFFEE', 3000, 'N', 1);
INSERT INTO MENU VALUES('A03', '카페라떼', 'COFFEE', 3500, 'N', 1);
INSERT INTO MENU VALUES('A04', '카페모카', 'COFFEE', 3500, 'N', 1);
INSERT INTO MENU VALUES('A05', '카라멜마끼야또', 'COFFEE', 4000, 'N', 1);
INSERT INTO MENU VALUES('A06', '바닐라라떼', 'COFFEE', 4000, 'N', 1);
INSERT INTO MENU VALUES('A07', '시그니처라떼', 'COFFEE', 4500, 'N', 1);
INSERT INTO MENU VALUES('A08', '흑당라떼', 'COFFEE', 4500, 'N', 1);
INSERT INTO MENU VALUES('A09', '콜드브루', 'COFFEE', 4500, 'N', 1);
INSERT INTO MENU VALUES('A10', '콜드브루연유라떼', 'COFFEE', 5000, 'N', 1);
INSERT INTO MENU VALUES('B01', '아이스티', 'TEA', 3000, 'N', 2);
INSERT INTO MENU VALUES('B02', '레몬에이드', 'ADE', 3500, 'N', 2);
INSERT INTO MENU VALUES('B03', '자몽에이드', 'ADE', 3500, 'N', 2);
INSERT INTO MENU VALUES('B04', '요거트스무디', 'SMOOTHIE', 5000, 'N', 2);
INSERT INTO MENU VALUES('B05', '딸기스무디', 'SMOOTHIE', 5000, 'N', 2);
INSERT INTO MENU VALUES('B06', '말차스무디', 'SMOOTHIE', 5000, 'N', 2);
INSERT INTO MENU VALUES('B07', '초코스무디', 'SMOOTHIE', 5000, 'N', 2);
INSERT INTO MENU VALUES('B08', '망고주스', 'JUICE', 5000, 'N', 2);
INSERT INTO MENU VALUES('B09', '키위주스', 'JUICE', 5000, 'N', 2);
INSERT INTO MENU VALUES('B10', '딸기주스', 'JUICE', 5000, 'N', 2);
INSERT INTO MENU VALUES('C01', '크로플', 'BREAD', 3500, 'N', 3);
INSERT INTO MENU VALUES('C02', '마카롱', 'BREAD', 2000, 'N', 3);
INSERT INTO MENU VALUES('C03', '허니브레드', 'BREAD', 5000, 'N', 3);
INSERT INTO MENU VALUES('C04', '오레오치즈케이크', 'BREAD', 5000, 'N', 3);
INSERT INTO MENU VALUES('C05', '치즈케이크', 'BREAD', 5000, 'N', 3);


-- DRINKSIZE 시퀀스 생성
CREATE SEQUENCE DRINKSIZESEQ;

-- DRINKSIZE 테이블 생성
CREATE TABLE DRINKSIZE(
DRINKSIZEID NUMBER PRIMARY KEY,
HOTSMALL VARCHAR2(45) NOT NULL,
ICESMALL VARCHAR2(45) NOT NULL,
HOTLARGE VARCHAR2(45) NOT NULL,
ICELARGE VARCHAR2(45) NOT NULL
);

SELECT * FROM DRINKSIZE;

INSERT INTO DRINKSIZE VALUES(1, '1', '2', '3', '4');








